### ISSUE TITLE
Technical review of error messaging solutions (part one)

### ISSUE THREAD

**Issue by MFarringtonRPF** [RaspberryPiFoundation/editor-api#186]
Here are the [draft product requirements](https://docs.google.com/document/d/1xikjqWWDQ4L76EB9kyELNUtkq5l_llliSCQAg5_Tsn8/edit) to bear in mind when assessing tech solutions. 

**Output**
- [x] Run a workshop / consultation within the Learner experience digital team and including Greg A to gather insights ready to complete [Technical review of error messaging solutions (part two: documentation)](https://github.com/orgs/RaspberryPiFoundation/projects/51/views/41#)

**Comment by sra405** [comment]
https://docs.google.com/document/d/1yTYEbJUSHHuAgjo-RnqmHXDClF9M-9Va4mb9H-8imEM/edit?usp=sharing
