### ISSUE TITLE
Investigate Latency

### ISSUE THREAD

**Issue by sra405** [RaspberryPiFoundation/editor-api#194]
We regularly get latency alerts regarding the editor API and have previously utilised Scout APM on our other products to help investigate.

The bullet gem has also been used to determine potential N+1s in development which could be an issue (see [here](https://github.com/RaspberryPiFoundation/codeclubworld/commit/9c7c0cf1e38540c00e03eb3b9e18bbcf0c33f637)).

![Image](https://user-images.githubusercontent.com/74183390/253084109-113775d7-efac-4798-9f32-8f4fc838eaaf.png)

Tasks:

- [ ] - Add Scout APM to Editor API heroku deployment
- [ ] - Setup Bullet on the Editor API to help tease out potential N+1s in development as part of normal testing.

**Comment by danhalson** [comment]
Terraform PR: https://github.com/RaspberryPiFoundation/terraform/pull/697
