### ISSUE TITLE
Start collecting errors and their associated code in the apps database

### ISSUE THREAD

**Issue by MFarringtonRPF** [RaspberryPiFoundation/editor-api#202]
~~We already appear to be catching and sending errors to Sentry, so we could tidy up this implementation to make the errors easier to read and interpret by making it clearer what sort of project triggered the error, adding the offending line of code etc...Sentry then gives us out of the box aggregation and tracking. 
Here's an example: https://rpf.sentry.io/issues/3742655621/?project=4504055099621376&query=is%3Aunresolved&referrer=issue-stream&stream_index=10
Authenticated users:
The url already provides the project name, but we should add the minimum info we need to be able to identify the user's project, probably just the `user_id`
Unauthenticated users:
We may want to deal with this at a later point because storing the code could be problematic - but if we could at a minimum extract the lines before and after the error, this could help with context.~~

------------------
**Start collecting the following data in the backend:**
One row per error instance - 
- Default Skulpt error message - containing all hints e.g. Syntax error, bad input, needs comma in line 3, relating to 'this is an example' string'. We want to be able to asses how likely any user typed strings contain data we wouldn't want to share with a 3rd party. 
- Time of error
- User ID
- Project URL

**Comment by sra405** [comment]
Rough breakdown:
- API to include new table
- UI to fire off events
- Remove Sentry for these errors
