### ISSUE TITLE
Disable graphiql on editor-api

### ISSUE THREAD

**Issue by danhalson** [RaspberryPiFoundation/editor-api#206]
Further to this discussion where @grega spotted graphiql was available on editor-api prod: https://raspberrypifoundation.slack.com/archives/C02JBAA2NFP/p1690910655530099

If you go to https://editor-api-production.herokuapp.com/, graphiql is currently available. Do we want to be making it so easy to query our api? Even if graphiql is disabled, introspection will still be possible via a third party graphql client, so maybe wider thought is required as to whether we disable introspection on production. 

More discussion is here: https://www.apollographql.com/blog/graphql/security/why-you-should-disable-graphql-introspection-in-production/

A possible approach is here in the accepted answer: https://stackoverflow.com/questions/54062534/disabling-graphql-introspection-requests-on-production

**Comment by grega** [comment]
Thanks Dan, just to note explicitly that https://editor-api.raspberrypi.org/ also renders this UI (ie. not just the herokuapp.com endpoint)

**Comment by sra405** [comment]
fix didn't work so reopening and putting into backlog 😕
