### ISSUE TITLE
Investigate Editor self-serve functionality

### ISSUE THREAD

**Issue by sra405** [RaspberryPiFoundation/editor-api#211]
Should've been wrapped up as part of https://github.com/RaspberryPiFoundation/digital-editor/issues/79 and could potentially be a very small fix to allow the content team to fully self-serve

- The [demo](https://github.com/raspberrypilearning/editor-content-process-demo) seemed to work in uploading a project that can be accessed here https://staging-editor.raspberrypi.org/en/projects/self-serve-demo 
- The self-serve process may need further user testing to check for any edge cases and make sure all aspects of the existing process have been replicated (including translations)
- If everything works then the [README](https://github.com/RaspberryPiFoundation/editor-api/blob/main/lib/tasks/README.md) on how to update projects needs updating.

**Comment by sra405** [comment]
https://raspberrypifoundation.slack.com/files/U08J95YCS/F05Q7GQKCMN/editor_api_problem_statement

**Comment by MFarringtonRPF** [comment]
@loiswells97 hopefully helpful notes starting from 'Current context' - https://docs.google.com/document/d/1RuTjqyYzHRgLZeguHwpoZFSHra-CICmZHps2aK6RKu8/edit
