### ISSUE TITLE
Check: remixed projects

### ISSUE THREAD

**Issue by sra405** [RaspberryPiFoundation/editor-api#227]
- [x] Check project remixed on save is available after login - save button is visible
- [x] Check it takes you to the remixed version of the project (when initially remixed) - also only a single remix is made
- [x] Ensure previous remixed project is loaded

**Comment by loiswells97** [comment]
There seem to be a lot of redirects when you remix and another one if you reload the page once you've got the remixed project - can we do anything to smooth this process for the user?

**Comment by loiswells97** [comment]
Marked as blocked until the ticket re-enabling auto-remixing has gone in
