### ISSUE TITLE
Separate organisation_id and primary id in Schools table

### ISSUE THREAD

**Issue by danhalson** [RaspberryPiFoundation/editor-api#273]
The Schools model currently expects the `organisation_id` from Profile to be the primary ID. This is problematic as we want to avoid creating an organisation in Profile until the school has been verified, however, the current implementation in the API does this, with a call to `ProfileApiClient.create_organisation`, though the response is stubbed.

In order to allow multiple schools to be created this call has been removed as of #267 and an `organisation_id` added to the Schools model.

This issue is refactor the API to ensure that all necessary calls reference the new `organisation_id`. This will undoubtedly cover all `ProfileApiClient` calls, however after some prodding about it was clear that this alone wasn't enough, and care needs to be taken to ensure the existing relationships aren't broken. Users (creators, teachers and students) will likely need updating too. Updating the factory with new ids should help identify potential problems.

**Comment by chrisroos** [comment]
We removed `School#organisation_id` in PR #281.
