### ISSUE TITLE
Model users' roles in editor-api

### ISSUE THREAD

**Issue by chrisroos** [RaspberryPiFoundation/editor-api#285]
- [x] https://github.com/RaspberryPiFoundation/editor-api/pull/292
- [x] https://github.com/RaspberryPiFoundation/editor-api/pull/293
- [x] https://github.com/RaspberryPiFoundation/editor-api/pull/294
- [x] https://github.com/RaspberryPiFoundation/editor-api/pull/296
- [x] https://github.com/RaspberryPiFoundation/editor-api/pull/298
- [x] https://github.com/RaspberryPiFoundation/editor-standalone/pull/152
- [x] https://github.com/RaspberryPiFoundation/editor-standalone/pull/156
- [ ] https://github.com/RaspberryPiFoundation/editor-api/pull/301

---

- [ ] #306
  - If a user has created a school then they shouldn't be able to see the /schools/new onboarding flow again. At present, the `/api/school` endpoint only returns the school that the user has a role in and not those they've created.
  - Add uniqueness constraint on `School#creator_id` to protect us against users creating more than one school
  - Add validation on `School` that prevents a user with a role in a school from creating a new school
- [ ] #308
- [ ] #307

**Comment by sra405** [comment]
Blocking aspects of this issue have been merged and deployed, other aspects have been separated out and added to the board

**Comment by chrisroos** [comment]
PRs/Issues that have been split out (I've removed them from the description so that all items in the description have been checked):

- https://github.com/RaspberryPiFoundation/editor-api/pull/301
- https://github.com/RaspberryPiFoundation/editor-api/issues/308
- https://github.com/RaspberryPiFoundation/editor-api/issues/307
- https://github.com/RaspberryPiFoundation/editor-api/issues/306
