### ISSUE TITLE
Invite a teacher

### ISSUE THREAD

**Issue by sra405** [RaspberryPiFoundation/editor-api#300]
As an Owner
I want to invite teachers at the school level by email
So that educators at my school can start to use the classroom management features

### Context

Now we know the roles are modelled in `editor-api` we'll need to handle the invite flow for roles associated with Raspberry Pi Accounts (i.e. `school-owner` and `school-teacher` roles).

### Related work

- UI implementation: https://github.com/orgs/RaspberryPiFoundation/projects/51/views/11?pane=issue&itemId=61570625

### Notes

Due to the disconnect between Pi Accounts and Editor API + the complication users being invited might not have an account there are several things that need to be considered, these include:

- Mechanisms for inviting teachers/owners via the frontend (see design)
- Storing the email/role (it was suggested we hash the email to avoid raw PII in `editor-api` for comparison when users login i.e. is there an outstanding invitation with the matching hash)
- Transactional emails to let them know they have an invited ([design](https://www.figma.com/design/SrINjD1MCT6VWYf1Yc9fV1/Code-Editor---Designs?node-id=5769-5022&t=hsrUvrZlXrLzDmNy-4))
- Accepting invites ([initial profile design](https://www.figma.com/design/SrINjD1MCT6VWYf1Yc9fV1/Code-Editor---Designs?node-id=5769-5018&t=hsrUvrZlXrLzDmNy-4))
- Retrieving the initial invite to set the role (unless we store the original invite we won't know at this stage what role to apply) - [design](https://www.figma.com/design/SrINjD1MCT6VWYf1Yc9fV1/Code-Editor---Designs?node-id=5769-5014&t=hsrUvrZlXrLzDmNy-4)

[design](https://www.figma.com/design/SrINjD1MCT6VWYf1Yc9fV1/Code-Editor---Designs?node-id=6783-96837&t=hsrUvrZlXrLzDmNy-4)

### PII concerns

An earlier version of this card suggested creating a technical implementation ADR in our internal docs [here](https://digital-docs.rpf-internal.org/docs/codebases/editor/). Mostly this was motiviated by a concern that we may end up needing to store PII (e.g. an email address to send an invitation email to, and possibly other information from the invitation) and we wanted to be sure that we were making a concious decision about that. 

We've decided to keep this issue in mind as we work on this story and when we get that far, to look at what, if any, problems we're creating and make sure we discuss them.

**Comment by sra405** [comment]
Current questions:
- we'd need to queue these transactional emails so emails will need to be stored in the backend
- how long will these role invitations last?
  - expire invites and delete PII (e.g. invite only lasts 30 days)

**Comment by chrislo** [comment]
I've started work adding the invitation of teachers via editor-api in https://github.com/RaspberryPiFoundation/editor-api/pull/312

**Comment by chrislo** [comment]
Closed in favour of this [epic card](https://github.com/orgs/RaspberryPiFoundation/projects/51/views/11?pane=issue&itemId=67112446). I've moved the relevant detail from this card to there.
