### ISSUE TITLE
Remove hardcoded user_ids and org_ids from users.json

### ISSUE THREAD

**Issue by sra405** [RaspberryPiFoundation/editor-api#308]

**Comment by floehopper** [comment]
@chrisroos Is this issue still relevant...?

**Comment by chrisroos** [comment]
@floehopper - I'd quite like to get rid of the users.json fixture file entirely but we'd have to check whether anything's still using it.

**Comment by floehopper** [comment]
@chrisroos :

It looks as if the only things that might need it relate to the `BYPASS_OAUTH` functionality and in the seeding code that @danhalson recently added:

https://github.com/RaspberryPiFoundation/editor-api/blob/41667ecbb687e876c6cf675eb9b683595a888378/lib/tasks/classroom_management_helper.rb#L5-L6

@danhalson Do you think we still need `users.json`?

**Comment by danhalson** [comment]
@floehopper no I don't think so, I added that uuid to the hash as this was the uuid assigned when BYPASS_OAUTH is used - it would make more sense for it to use an id for jane or john doe going forward
