### ISSUE TITLE
Update the school code (and maybe project slugs) to use numbers

### ISSUE THREAD

**Issue by sra405** [RaspberryPiFoundation/editor-api#313]
### User needs
As an Owner/Teacher
I need to see my **unique, easy-to-copy-by-hand** school code displayed prominently on my dashboard
So that I can share it with my students quickly and easily

As a student user, 
I need my school code to be easy to type
So that I can log in with it easily

**NFRs:**
- School code must be unique for obvious reasons
- Format needs to be scalable and easy to copy
  - **Agreed format:** 11-22-33-44

Notes on the 11-11-11-11 format: 
- It is scalable 
- Futureproofed for localisation (rather than needing a separate list of words for each language)
- Usability - don't need to worry about typos in spelling words; we are likely to be used by lots of EAL/ESL from the outset, so it is one place we can make this easier for those users (without full localisation)
- Feels counterintuitive to not use learnings and improve with new implementations  which would get very hard to maintain.

----
### Tech notes

On verifying a school a "school code" is assigned. This is used and surfaced in a few places:

- Teachers/owners can see if on their dashboard - [design](https://www.figma.com/design/SrINjD1MCT6VWYf1Yc9fV1/Code-Editor---Designs?node-id=6759-78824&t=QyKXDQjj9lOIabgO-4)
- Student accounts are scoped to the "school code" so is passed to profile via the [student API](https://my.raspberrypi.org/api/v1/documentation/#/Students). Note from Scott 12/06: Without this we won't be able to create students. We need to pass over the school code to profile so the student login works and we scope the students to the right school.
- Student login pages in profile will use the "school code" as the slug

Many different approaches to this but I suggest:

- Adding a "school code" field to the "schools" table
- Using the same mechanism as the projects slug to assign a school slug
- Add this to the school verification flow
- Add a call to profile [school API](https://my.raspberrypi.org/api/v1/documentation/#/Schools) to add the "school code" to profile for future student scoping
- Add the frontend component to surface the code to teachers/owners

**Comment by MFarringtonRPF** [comment]
What do you want to do with this @sra405 ? Can it be closed?
