### ISSUE TITLE
Add student data to dev seeds

### ISSUE THREAD

**Issue by danhalson** [RaspberryPiFoundation/editor-api#339]
Once unblocked, add student data to dev seeds - student seeds were added to profile here: https://github.com/RaspberryPiFoundation/profile/pull/1627/files

**Comment by danhalson** [comment]
Blocked by https://github.com/RaspberryPiFoundation/editor-standalone/issues/182

**Comment by sra405** [comment]
@danhalson if you're ok having a check in with core about this that'd be great. I get the feeling Jane and John Smith are almost good to go 👀

**Comment by danhalson** [comment]
@sra405 the core side of this is done, the blocker was the api integration on our side...but maybe all that's needed is a record added to class_members now, assuming no other changes? will take a look

**Comment by sra405** [comment]
> @sra405 the core side of this is done, the blocker was the api integration on our side...but maybe all that's needed is a record added to class_members now, assuming no other changes? will take a look

Yea I think so too, we can assume the API links will be done and if the profile side of things is done that means both Jane and John Smith have uuids too. It'd just be worth assigning one to a class and leaving the other unassigned.

What would be worth doing too is setting the school code for this dummy school too and either seeding the profile side of things ourselves as part of this or letting core know the uuid & code of the school so the student login side of things works too
