### ISSUE TITLE
Explicit CORS Update

### ISSUE THREAD

**Issue by sra405** [RaspberryPiFoundation/editor-api#405]
Currently all our CORS URLs are set in environment variables in terraform for [staging](https://github.com/RaspberryPiFoundation/terraform/blob/5e4884626fc4d9fb84fa8b1083d7aab8d6f690c3/projects/editor-api/nonprod/terraform.tfvars#L19) and [prod](https://github.com/RaspberryPiFoundation/terraform/blob/5e4884626fc4d9fb84fa8b1083d7aab8d6f690c3/projects/editor-api/prod/terraform.tfvars#L18).

The CORS policies are set [here](https://github.com/RaspberryPiFoundation/editor-api/blob/08d36c56cf50c9da9e7ff6489179fa47bfe8f471/config/initializers/cors.rb) and just take the env var and separate the list on commas.

I'd like a more explicit set of CORS policies in the app similar to [badge-service](https://github.com/RaspberryPiFoundation/badge-service/blob/main/config/initializers/cors.rb). By doing these we'll also be able to wildcard specific subdomains to allow things like review apps to load the staging editor correctly!

### Other context

[CORP middleware](https://github.com/RaspberryPiFoundation/editor-api/blob/08d36c56cf50c9da9e7ff6489179fa47bfe8f471/lib/corp_middleware.rb) also utilises `ALLOWED_ORIGINS` to set headers required for accessing images from the web component. This could be altered too because it only uses the URLs without `https://` (a little ropey) but these are the API URLs (i.e. `staging-editor-api.raspberrypi.org` for staging and `editor-api.raspberrypi.org` for prod).

### Notes

Here's a list of URLs we need to include in the CORS policy

staging:

```
staging-editor-api.raspberrypi.org, (CORP middleware)
https://*.raspberrypi.org,

https://editor-standalone-eyq.pages.dev, (editor.raspberrypi.org CF pages build)
https://*.editor-standalone-eyq.pages.dev, (NEW - wildcard ones currently don't work so review apps don't load data)
https://block-to-text-alpha.pages.dev, (soon to be removed and deprecated so maybe a good candidate to leave in `ALLOWED_ORIGINS`)
https://projects-ui.pages.dev, (projects.raspberrypi.org CF pages build)
https://*.projects-ui.pages.dev, (NEW - wildcard ones currently don't work so review apps don't load data)

// REQUIRED FOR OAK
https://studio.edx.org,
https://preview.courses.edx.org,

// REQUIRED FOR LOCAL DEV
http://localhost:3001,http://localhost:3010,http://localhost:3011,http://localhost:3012
```

**Comment by grega** [comment]
Rather than follow badge-service to the letter (which implements some hard-coded origin regexes), I've taken a slightly different approach in https://github.com/RaspberryPiFoundation/editor-api/pull/409 which continues to assume all non-dev/non-test values are set in the environment, but allows for regex / wildcard matching.

**Comment by grega** [comment]
@sra405 I don't quite understand this bit:

> This could be altered too because it only uses the URLs without https:// (a little ropey)

Are we not using https URLs for serving static assets? 🤔
